### ISSUE TITLE
Timetables now available for Mendocino

### ISSUE THREAD

**Issue by evantrillium** [Trillium-Solutions/mendocino-wp-theme#1]
Per https://trilliumtransit.zendesk.com/agent/tickets/52334

@websites we're takiung back Mendocino! somehow

it's timetables are...not
example: https://mendocinotransit.org/routes/route-65/northbound/

but good news! we now have
1) updated their schedules
2) made tts
3) they all look good on my end except 7/9, which is multiroute so I can't run it on my own.

options
1) your team attempts to tcp-ify the website, a la tart
2) my team uses html to attempt update via WP (I don't see anything on sftp, but I also haven't been on this site in forever)
3) do nothing at this time

from @ekeaton 
1. Mendo is much older than TART and isn't linked to TCP at all. TART was, it just used Tablepress, so the process was half done and pretty smooth-ish-ish. Mendo would require a larger website overhaul to get set up with TCP at this time. 
2. Mendo only uses SFTP for PDF's so you're right TT's aren't uploaded there. They are done via the timetable pages in WP. Example here: https://mendocinotransit.org/wp-admin/post.php?post=1723&action=edit

Many moons ago when I took all their TT's down, I just removed the times from the TT's and not the HTML tables themselves, so the structure is all there. Their HTML looks custom-like, semi-similar to YARTS. But if you want to go rouge with the generic tt's from g2h...
To find a tt for a route in WP pages, use the search bar and search "Route - (number of route) - (direction).
3. Yes! :) 

cc @danielleogden @NomeQ

**Comment by evantrillium** [comment]
staging updated with vanilla html tts 
http://mdcinostaging.wpengine.com/
[mendo_tts.zip](https://github.com/Trillium-Solutions/mendocino-wp-theme/files/5740526/mendo_tts.zip)

note that tts for route 9 are missing values from route 7, since that's a multiroute tt and I can't run that

**Comment by NomeQ** [comment]
I think we would ideally like to get TCP set up for Mendocino. However, it would need to be a paid project, not "free cookies", since it could take as much as 20 hours of work to set up. We could waive or charge for half of it, and it might end up faster than 20 hours, but I don't see it working as a free bonus.

Longterm goal: TCP, plus actually have timetables on the route pages, not as standalone links.

I say let's start the first part of that longterm goal by switching to the default g2h timetables. @ekeaton can you add styles to the theme css to make them look reasonable?

**Comment by schurnsi** [comment]
@NomeQ Mendocino signed an order form today for "website accessibility upgrades".. Just fyi, in case that changes any processes you were about to embark on. @danielleogden

**Comment by evantrillium** [comment]
woohoo!

also, @ekeaton you should definitely run g2h yourself on these tts - 7/9 is multiroute and there are probably other improvements you will have. They should work fine otherwise (I already cleaned them up in timetable_stop_order.txt as much as possible)

**Comment by ekeaton** [comment]
@evantrillium Are routes 1 and 20 multi-routes also? I see from what they use to have it was a combined schedule https://mendocinotransit.org/routes/routes-1-and-20/route-1-and-20-southbound-aug-2013/

**Comment by evantrillium** [comment]
1/20 isn't technically multiroute - it's just two timetables on the same page. Not sure best way to do that.

7/9 are true multiroute in that they cover the same area (one is an express and one is local)

**Comment by ekeaton** [comment]
@NomeQ aka Nomette.

After running g2h and looking at the current site. I think a bit more leg work needs to be done. For instance right now if you visit Routes 7/9. (Which is a multi-route) https://mendocinotransit.org/routes/routes-7-and-9/
The Route sections are split. One for 7 and one separate for 9. 

It would make more sense if 7/9's page looked more like this (https://mendocinotransit.org/routes/routes-1-and-20/)

And then since 1 and 20 or separate schedules, change that page to look the way 7/9 currently looks. With one box for Route 1 with respective links, followed by a box below for Route 20. 
Same would go for 5 and 60.

Thoughts?

**Comment by evantrillium** [comment]
I think it may be worthwhile for @danielleogden to meet with Jacob King at Mendo and confirm route organization before we do too much work on this, particularly because multiroute tts are harder to make/take apart in gtfsm than regular tts.

I think we want to convey the following about multiroute tts:

1) they are most effective when two or more routes have overlapping stops (most mendo routes don't overlap - they simply represent connections between intercity and local routes)

2) they do not (as of now) generate multi-route trips - so even if a bus continues onto another route (eg, an intercity bus continues to provide local service), the tt generated by g2h won't show that as a single column (in a horizontal tt) or row (in a vertical tt).

The pdfs tend to contain multi route where they are showing transfers or interlining, neither of which g2h really captures right now. Not saying it's impossible, and *definitely* not saying we should go back to manual tts that show this, but we should ensure Mendo understands the benefits of g2h tts, as well as their options for displaying related or similar services.

**Comment by ekeaton** [comment]
I think it would be good to set up a meeting between all of us initially to chat a bit about the options to bring to the client so we're all on the same page first. @danielleogden Would you like to set one up?

**Comment by danielleogden** [comment]
@ekeaton I think that would be helpful for me! I'll send an invite.

**Comment by danielleogden** [comment]
Noting that I emailed Jacob this afternoon with our proposal to split up all route pages/tables other than 7/9. I'll update when I get a response.

**Comment by danielleogden** [comment]
I heard back from Luis Martinez, Mendocino Operations Supervisor, and he said they are fine with us splitting the routes and timetables that are not multi-routes. @evantrillium he also said that route 7 is not currently running, which I believe you already mentioned. He confirmed that PDFs on the website are the most up-to-date schedule info. Let me know if we need anything else from them. 

He said they are under Caltrans pressure to have the timetables up by Jan 22. That seems like a reasonable amount of time, but let me know if there's any reason we don't think that can be done. 

@NomeQ he also asked about the accessibility updates. Do you have a ballpark of when those updates can be completed? I believe there's less pressure to have those done soon.

**Comment by evantrillium** [comment]
I still had two trips on route 7 - I will map those to route 9 and re-export.

**Comment by evantrillium** [comment]
new feed posted to --ttable.zip @ekeaton let me know how 7/9 looks. There are two library stops so the stop time for it on the first trip will probably have to be manually entered

**Comment by ekeaton** [comment]
[Mendo-2.zip](https://github.com/Trillium-Solutions/mendocino-wp-theme/files/5797451/Mendo-2.zip)
@evantrillium

**Comment by evantrillium** [comment]
@ekeaton thanks - I will tweak 7/9 and post here for you shortly

**Comment by NomeQ** [comment]
@danielleogden re:accessibility updates - I think that realistically, I am too busy to take on any more dev tasks. Apart from urgent support and the tasks I've already put on my plate, I think we should assume scheduling all of these is dependent on hiring a new full-time dev.

If we haven't succeeded in hiring someone toward the end of the month, let's check back in about Mendo accessibility (and other outstanding dev tasks), and I'll make a plan for fitting them in my schedule, pairing with Estelle, or figuring out what we can contract out to stay on top of everything.

**Comment by danielleogden** [comment]
@NomeQ Thanks, I think that will work. I'll update the client with these expectations.

**Comment by evantrillium** [comment]
new --table posted with some tweaks to rt 9 and an additional trip added
I looked at my output and it was 95% there - I can make some small edits on staging (eg, adding a stop time to library for a run that won't show it because of stop assignments, and some indicator that the last sb run hits plowshares)

**Comment by ekeaton** [comment]
@danielleogden @evantrillium @NomeQ @everyone behold. Updated Mendo on staging for timetables and Route pages. https://mdcinostaging.wpengine.com/

I also updated how their PDF's system, so now they can directly add a PDF in WP. Instead of us doing so in SFTP.

**Comment by evantrillium** [comment]
this is looking great! I added a few changes to rt 9 - @danielleogden there are more notes in rt 9 that we could probably include in the tt right now, but I think we want to wean them off those notes because they aren't compatible with g2h and we don't want to do tons of post export edits on this route

**Comment by danielleogden** [comment]
@evantrillium my QC review can be found [here](https://docs.google.com/document/d/1bfh62adGXi2l6uUfavsqHrRrcIRl9MDszMLIzqzb1FY/edit?usp=sharing). Mostly questions or corrections to the GTFS or timetable display. 

@ekeaton I think this issue may be something for you to handle:
Deprecated route 66 still showing in route selector on route pages.

**Comment by danielleogden** [comment]
@evantrillium I've reviewed your comments and I'm satisfied with the changes. Can you provide an updated --ttable file?

Issues for @ekeaton 

- [ ] Remove deprecated route 66 from route selector on route pages.
- [ ] Update config file to show arrivals for Hillside Valley stop on Route 9/7 Southbound.

**Comment by danielleogden** [comment]
@ekeaton I realized Evan is out until Thursday, so I had Sara produce the new feed. She says it's ready at the fetch location. No urgency to get this done today, but we want to make sure everything is ready by/before Friday. I also emailed Luis to get a confirmation on which schedule PDFs are the most recent.

**Comment by ekeaton** [comment]
@danielleogden I removed the deprecated route 66 from the route selector on route pages. The update is on staging https://mdcinostaging.wpengine.com/

As for updating the config to show arrivals for Hillside Valley, no lo sé, I ran g2h with:
 - showOnlyTimepoint: true and as false
- with a templatePath using both the trillium and timetable templates. Then without a template.
- Using the newest version of g2h and the older version. 
- 
But it still shows those times as "Request call for pickup"

**Comment by danielleogden** [comment]
@ekeaton Thank you, route menu looks good. Have all the timetables been updated?

@evantrillium for Hillside Valley stop, the arrival times are actually missing from the GTFS schedules. According to the PDF, this should be one of those with both an arrival time and a request stop symbol. Can you update this one tomorrow?

**Comment by ekeaton** [comment]
@danielleogden Si, all the timetables you mentioned have been updated.

**Comment by danielleogden** [comment]
@ekeaton was 75 updated? I'm still seeing the directions swapped. 
Then once @evantrillium updates the Hillside Valley stop on Route 9/7, we will be all set. 

It looks like my pdf updates were lost. :( 
Would it be easier if I just update those after we make the tts live?

**Comment by ekeaton** [comment]
@danielleogden On staging? I'm still seeing the current PDFs there? But if they look different than yes, just to be safe updating on Production might be best. 

As for 75 the timetables look the same, that I just ran. What changes are needed for that Route?

**Comment by danielleogden** [comment]
@ekeaton for 75: the schedule starting at Raley's should be under Southbound and the one starting at the Gualala Mall should be Northbound. Right now they are swapped.

**Comment by ekeaton** [comment]
@danielleogden Got it! I swapped them!

**Comment by evantrillium** [comment]
http://mdcinostaging.wpengine.com/routes/routes-7-and-9/route-7-and-9-southbound/
updated

**Comment by danielleogden** [comment]
@ekeaton Ok I think we are good to make this live!

**Comment by ekeaton** [comment]
All systems are a go! And we're [live](https://mendocinotransit.org/) everyone. *insert rocket taking off here.

**Comment by danielleogden** [comment]
Looks great! Thanks @ekeaton and @evantrillium! 

For some reason all the old pdfs were giving a 404 error. I had to update them with the new ones anyway, but just thought I should note!

**Comment by ekeaton** [comment]
Solving, since we're now live!
