### ISSUE TITLE
Main Nav Improvements

### ISSUE THREAD

**Issue by NomeQ** [Trillium-Solutions/mendocino-wp-theme#28]
- [x] Fares icon is hard to see, too detailed for this size. Replace with simpler icon.
- [x] Clock icon for schedules doesn't match style of "info" icon - find a clock that uses thicker line widths
- [x] Add hover/focus styles for nav items that matches live site (box around nav item)

**Comment by NomeQ** [comment]
- [ ] Icons in main nav should have `alt=""` -- because both the icon and the text are inside the link, the screen reader will use that text, and the icons are just for decoration.

Just a note that alt text should be descriptive, not a title. So if these icons did require alt text, good alt text would just be "Maps and Schedules" and "Fares" - a description of what the icon means (and where the link goes).

**Comment by ekeaton** [comment]
@NomeQ I included alt-text for all the icons the first go. Are they not showing up? Each one says icon then what the icon is for.

**Comment by NomeQ** [comment]
Currently, alt text for the maps and schedules button is `<img alt="icon-maps-and-schedules">`. Because this element is purely decorative, and does not add any meaning beyond the text that is already in the link, it should have empty alt text, e.g. `<img alt="">`. Including an empty string lets it know that the alt text is not missing, but the image is purely decorative.

However, **if** it was not purely decorative, you would still want to change the alt text to be human-readable. Right now, a screen reader would read that letter by letter, due to the hyphens. You'd want it to just say `<img alt="maps and schedules">`.

**Comment by ekeaton** [comment]
o0oooooooooooooooooooo! Got it! I didn't realize when you put `alt=""` that you actually meant an empty string. I took it as .. place text here and thought "it's there.." :D. Sorry!

**Comment by NomeQ** [comment]
- Keep nav items from shifting on hover. Do this by always having the border applied - use a transparent border when the element is not being interacted with, then apply the border color on hover. 
- Don't apply an underline on hover to the nav elements

**Comment by NomeQ** [comment]
Items still move on hover - also ensure no padding is added on hover- ensure it exists on the base element to prevent this.

**Comment by ekeaton** [comment]
got it! I had width added oops.
