### ISSUE TITLE
"When" form control in homepage planner not labeled correctly

### ISSUE THREAD

**Issue by NomeQ** [Trillium-Solutions/mendocino-wp-theme#29]
We'll have to change up the base styles from the site here, because each input needs a label associated with it, and "When" is being applied to multiple elements. "Date" and "Time" need associated labels, as does the dropdown select, I suggest "Depart" for that label.

**Comment by ekeaton** [comment]
@NomeQ I made my edits on index.php not new-home.php as that seemed to be the template actually being used. Let me know if i still need to make these edits if that's where you were already looking!
