### ISSUE TITLE
Add HTML5 Landmarks to the theme code

### ISSUE THREAD

**Issue by NomeQ** [Trillium-Solutions/mendocino-wp-theme#3]
Can copy the basic skeleton theme we use for all our sites, adding at minimum a `<header>`, `<footer>`, `<main>` and `<aside>` for all pages.

Note that `<aside>` is used for a sidebar element, if it exists.

**Comment by NomeQ** [comment]
Close out elements correctly - right now everything on the page is enclosed within the `<header>` element

**Comment by ekeaton** [comment]
@NomeQ I completely forgot to add a note to this one. I'm having trouble figuring out how/where to close the header element thats I put in header.php. Due to the background image that's applied within that file. When I close it out it throws off the whole site.

**Comment by NomeQ** [comment]
@ekeaton good question - it's such an old school site that it really is structured differently. I'll take a look and see if I see any good strategies.

**Comment by NomeQ** [comment]
Best bet is to just wrap the `<header>` element around the `<div id="top">` element
