### ISSUE TITLE
Summary of ADA changes

### ISSUE THREAD

**Issue by danielleogden** [Trillium-Solutions/mendocino-wp-theme#36]
Please help me put together a summary of the accessibility improvements we made to Mendocino. They just need something to provide to Caltrans to show what was done. Probably best if it's pretty high level descriptions. Can you just get a doc started with the list of improvements? Then I can flesh it out and make it look official.

**Comment by ekeaton** [comment]
I shared a doc with you (sent to your email) with a high overview list of the updates main
