### ISSUE TITLE
Route 7 issue

### ISSUE THREAD

**Issue by danielleogden** [Trillium-Solutions/mendocino-wp-theme#38]
From client:
On our landing page there’s a blue circle with the route 7 for a link. The link takes us to the route 75 which is incorrect. The 7 is a Ukiah route that we are not currently using. The other link inside the schedule page also links to 75 can we just put a temp page that says due to the pandemic we do not currently have a route 7? Thanks

**Comment by danielleogden** [comment]
@ekeaton maybe this is something @MarkTrillium can do?

**Comment by MarkTrillium** [comment]
@danielleogden I created the route 7 page and the links on the map and schedule page are correctly redirecting to Route 7. Added text to Route 7 indicating the route has been suspended due to Covid.
